const controller = require("../controllers/analytics.controller");
const { authJwt } = require("../middleware");


module.exports = function(app) {
   app.use(function(req, res, next) {
     res.header(
       "Access-Control-Allow-Headers",
       "x-access-token, Origin, Content-Type, Accept"
     );
     next();
   });
  /**
  * @swagger
  *tags:
  *  name: Analytics
  *  description: API to manage the analytics returns.
  */
   /**
  * @swagger
  *tags:
  *  name: Overview Dashboard
  *  description: API to manage the overview dashboard results.
  */


/**
  * @swagger
  * /api/analytics/loitering/{id}:
  *   post:
  *    tags:
  *       - Analytics
  *    summary: "Loitering analytic's results"
  *    operationId: loitering
  *    description: "Use to obtain results from Loitering algorithm for an specific camera under a range of time"
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: true
  *               data:
  *                 type: object
  *                 properties:
  *                   total:
  *                     description: "Total alerts"
  *                     type: number
  *                     example: 156
  *                   avgH:
  *                     description: "Avarage in hours"
  *                     type: number
  *                     example: 32.1
  *                   avgS:
  *                     description: "Avarage in seconds"
  *                     type: string
  *                     example: 12.1
  *                   raw:
  *                     description: "Raw data from MySQL."
  *                     type: array
  *                     example: []                         
  *                   dwell:
  *                     description: "Array with the values of dwell"
  *                     type: array
  *                     example: []
  *                   labelsD:
  *                     description: "Labels for the detection times in array format"
  *                     type: array
  *                     example: []
  *                   histogram:
  *                     description: "Counts for the histogram" 
  *                     type: object
  *                     example: {}
  *                   min:
  *                     description: "Minimun value for the time variation"
  *                     type: number
  *                     example: 10
  *                   max:
  *                     description: "Maximun value for the time variation"
  *                     type: number
  *                     example: 12
  *                   avg:
  *                     description: "Avarage value for the time variation"
  *                     type: number
  *                     example: 11.5
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
   app.post(
    "/api/analytics/loitering/:id",
    [authJwt.verifyToken],
    controller.loitering
  );

  app.get(
    "/api/analytics/loitering/alerts",
    [authJwt.verifyToken],
    controller.loiteringAlerts
  );

  app.get(
    "/api/analytics/loitering/alerts/:id",
    [authJwt.verifyToken],
    controller.loiteringAlerts
  );

/**
  * @swagger
  * /api/analytics/intrude/{id}:
  *   post:
  *    tags:
  *       - Analytics
  *    summary: "Intrusion Alert results"
  *    operationId: intrude
  *    description: "Use to obtain results from Intrusion Alert algorithm for an specific camera under a range of time"
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: true
  *               data:
  *                 type: object
  *                 properties:
  *                   total:
  *                     description: "Total alerts"
  *                     type: number
  *                     example: 156
  *                   avgH:
  *                     description: "Avarage in hours"
  *                     type: number
  *                     example: 32.1
  *                   raw:
  *                     description: "Raw data from MySQL."
  *                     type: array
  *                     example: []                         
  *                   donut:
  *                     description: "Array with the values for the pie chart"
  *                     type: array
  *                     example: []
  *                   over:
  *                     description: "Over time data graph"
  *                     type: object
  *                     example: {}
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/intrude/:id",
    [authJwt.verifyToken],
    controller.intrude
  );

  app.get(
    "/api/analytics/intrude/alerts",
    [authJwt.verifyToken],
    controller.intrudeAlerts
  );

  /**
  * @swagger
  * /api/analytics/violence/{id}:
  *   post:
  *    tags:
  *       - Analytics
  *    summary: "Violence algorithm's results"
  *    operationId: violence
  *    description: "Use to obtain results from Violence algorithm for an specific camera under a range of time"
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/violence/:id",
    [authJwt.verifyToken],
    controller.violence
  );

  /**
  * @swagger
  * /api/analytics/aod/{id}:
  *   post:
  *    tags:
  *       - Analytics
  *    summary: "Abandoned Object analytic's results"
  *    operationId: aod
  *    description: "Use to obtain results from Abandoned Object algorithm for an specific camera under a range of time"
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/aod/:id",
    [authJwt.verifyToken],
    controller.aod
  );
/**
  * @swagger
  * /api/analytics/covered/{id}:
  *   post:
  *    tags:
  *       - Analytics
  *    summary: "No Mask analytic's results"
  *    operationId: covered
  *    description: "Use to obtain results from No Mask algorithm for an specific camera under a range of time"
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/covered/:id",
    [authJwt.verifyToken],
    controller.covered
  );

  app.get(
    "/api/analytics/covered/alerts",
    [authJwt.verifyToken],
    controller.coveredAlerts
  );

/**
  * @swagger
  * /api/analytics/social/{id}:
  *   post:
  *    tags:
  *       - Analytics
  *    summary: "Social Distance analytic's results"
  *    operationId: social
  *    description: "Use to obtain results from Social Distance algorithm for an specific camera under a range of time"
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/social/:id",
    [authJwt.verifyToken],
    controller.social
  );

  app.get(
    "/api/analytics/social/alerts",
    [authJwt.verifyToken],
    controller.socialAlerts
  );

/**
  * @swagger
  * /api/analytics/pc/{id}:
  *   post:
  *    tags:
  *       - Analytics
  *    summary: "People Count analytic's results"
  *    operationId: pc
  *    description: "Use to obtain results from People Count algorithm for an specific camera under a range of time"
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/pc/:id",
    [authJwt.verifyToken],
    controller.pc
  );

  /**
  * @swagger
  * /api/analytics/helm/{id}:
  *   post:
  *    tags:
  *       - Analytics
  *    summary: "Helmet Detection analytic's results"
  *    operationId: helm
  *    description: "Use to obtain results from Helmet Detection algorithm for an specific camera under a range of time"
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/helm/:id",
    [authJwt.verifyToken],
    controller.helm
  );

  /**
  * @swagger
  * /api/analytics/queue/{id}:
  *   post:
  *    tags:
  *       - Analytics
  *    summary: "Queue Management analytic's results"
  *    operationId: queue
  *    description: "Use to obtain results from Queue Management algorithm for an specific camera under a range of time"
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/queue/:id",
    [authJwt.verifyToken],
    controller.queue
  );

  app.get(
    "/api/analytics/queue/alerts",
    [authJwt.verifyToken],
    controller.queueAlerts
  );

/**
  * @swagger
  * /api/analytics/vault/{id}:
  *   post:
  *    tags:
  *       - Analytics
  *    summary: "Open Vault Door analytic's results"
  *    operationId: vault
  *    description: "Use to obtain results from Open Vault Door algorithm for an specific camera under a range of time"
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/vault/:id",
    [authJwt.verifyToken],
    controller.vault
  );

/**
  * @swagger
  * /api/analytics/parking/{id}:
  *   post:
  *    tags:
  *       - Analytics
  *    summary: "Parking Violation analytic's results"
  *    operationId: parking
  *    description: "Use to obtain results from Parking Violation algorithm for an specific camera under a range of time"
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/parking/:id",
    [authJwt.verifyToken],
    controller.parking
  );

  /**
  * @swagger
  * /api/analytics/anpr/{id}:
  *   post:
  *    tags:
  *       - Analytics
  *    summary: "Automatic Number Plate Recognition (ANPR) analytic's results"
  *    operationId: anpr
  *    description: "Use to obtain results from Automatic Number Plate Recognition (ANPR) algorithm for an specific camera under a range of time"
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/anpr/:id",
    [authJwt.verifyToken],
    controller.anpr
  );

  /**
  * @swagger
  * /api/analytics/barrier/{id}:
  *   post:
  *    tags:
  *       - Analytics
  *    summary: "Barrier Detection analytic's results"
  *    operationId: barrier
  *    description: "Use to obtain results from Barrier Detection algorithm for an specific camera under a range of time"
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/barrier/:id",
    [authJwt.verifyToken],
    controller.barrier
  );

  /**
  * @swagger
  * /api/analytics/vehicle/{id}:
  *   post:
  *    tags:
  *       - Analytics
  *    summary: "Vehicle Count analytic's results"
  *    operationId: vehicle
  *    description: "Use to obtain results from Vehicle Count algorithm for an specific camera under a range of time"
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/vehicle/:id",
    [authJwt.verifyToken],
    controller.vc
  );

  /**
  * @swagger
  * /api/analytics/queueLite/{id}:
  *   post:
  *    tags:
  *       - Overview Dashboard
  *    summary: "Queue Managemente Lite results"
  *    operationId: queueLite
  *    description: "Use to obtain results from Queue Managemente algorithm for an specific camera under a range of time. This is the lite version to load main Dashboard overview."
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/queueLite/:id",
    [authJwt.verifyToken],
    controller.queueLite
  );

/**
  * @swagger
  * /api/analytics/pcLite/{id}:
  *   post:
  *    tags:
  *       - Overview Dashboard
  *    summary: "People Count lite results"
  *    operationId: pcLite
  *    description: "Use to obtain results from People Count algorithm for an specific camera under a range of time. This is the lite version for Overview Dashboard."
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/pcLite/:id",
    [authJwt.verifyToken],
    controller.pcLite
  );

/**
  * @swagger
  * /api/analytics/premises/{id}:
  *   post:
  *    tags:
  *       - Overview Dashboard
  *    summary: "Premises overview results"
  *    operationId: premises
  *    description: "Use to obtain results from Premises for an specific camera under a range of time. This is for the main overview Dashboard."
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/premises/:id",
    [authJwt.verifyToken],
    controller.premises
  );

  /**
  * @swagger
  * /api/analytics/threats/{id}:
  *   post:
  *    tags:
  *       - Overview Dashboard
  *    summary: "Threats overview results"
  *    operationId: threats
  *    description: "Use to obtain results from Threats for an specific camera under a range of time. This is for the main overview Dashboard."
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/threats/:id",
    [authJwt.verifyToken],
    controller.threats
  );
  /**
  * @swagger
  * /api/analytics/tamper/{id}:
  *   post:
  *    tags:
  *       - Analytics
  *    summary: "Camera Tamper analytic's results"
  *    operationId: tamper
  *    description: "Use to obtain results from Camera Tamper algorithm for an specific camera under a range of time"
  *    parameters:
  *      - in: path
  *        name: id
  *        schema:
  *          type: string
  *        required: true
  *      - in: header
  *        name: x-access-token
  *        schema:
  *          type: string
  *        required: true
  *    requestBody:
  *       content:
  *          application/json:
  *            schema:
  *              type: object
  *              properties:
  *                type:
  *                  description: "Type of data to be retrieved. Can be cam_id, id_branch or id_account."
  *                  type: string
  *                  example: cam_id
  *                start:
  *                  description: "Date for initial range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-10-01T03:00:00.000Z
  *                end:
  *                  description: "Date for end range. Format: 2020-10-01T03:00:00.000Z."
  *                  type: string
  *                  example: 2020-11-01T02:59:59.000Z
  *    responses:
  *      '200':
  *        description: "A successful response"
  *      '500':
  *        description: "Server error"
  *        content:
  *          application/json:
  *            schema:
  *             type: object
  *             properties:
  *               success:
  *                 description: "Result type"
  *                 type: boolean
  *                 example: false
  *               message:
  *                 description: "Type of failure"
  *                 type: string
  *                 example: Error message generated by the server
 */
  app.post(
    "/api/analytics/tamper/:id",
    [authJwt.verifyToken],
    controller.tamper
  );
}