const { verifySignUp, authJwt } = require('../middleware')
const controller = require('../controllers/auth.controller')

/**
 * @swagger
 *tags:
 *  name: Account
 *  description: API to manage accounts settings.
 */

module.exports = function (app) {
  app.use(function (req, res, next) {
    res.header('Access-Control-Allow-Headers', 'x-access-token, Origin, Content-Type, Accept')
    next()
  })

  /**
   * @swagger
   * /api/auth/signup/client:
   *   post:
   *    tags:
   *       - Account
   *    summary: "Sign up Client"
   *    operationId: signUpClient
   *    description: "Use to register a client with required options."
   *    parameters:
   *      - in: header
   *        name: x-access-token
   *        schema:
   *          type: string
   *        required: true
   *    requestBody:
   *       content:
   *          application/json:
   *            schema:
   *              type: object
   *              properties:
   *                username:
   *                  description: "Username"
   *                  type: string
   *                  example: test
   *                password:
   *                  description: "Password"
   *                  type: string
   *                  example: test
   *                email:
   *                  description: "Email"
   *                  type: string
   *                  example: test@gmail.com
   *                unique:
   *                  description: "Unique"
   *                  type: boolean
   *                  example: true
   *                cameras:
   *                  description: "No. of Cameras to be available"
   *                  type: number
   *                  example: 5
   *                analytics:
   *                  description: "Analytics to be available"
   *                  type: number
   *                  example: testAnalytics
   *                vms:
   *                  description: "VMS"
   *                  type: string
   *                  example: testVMS
   *                algorithm:
   *                  description: "Algorithm"
   *                  type: string
   *                  example: testAlgorithm
   *    responses:
   *       '201':
   *         description: "User Created"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                message:
   *                  description: "Response Message"
   *                  type: string
   *                  example: User was registered successfully!
   *       '500':
   *         description: "Internal Server error"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *               message:
   *                 description: "Response Message"
   *                 type: string
   *                 example: Error message generated by the server
   */
  app.post(
    '/api/auth/signup/client',
    [
      verifySignUp.checkDuplicateUsernameOrEmail,
      authJwt.verifyToken,
      authJwt.isAdmin
    ],
    controller.signupClient
  )

  /**
   * @swagger
   * /api/auth/signup/admin:
   *   post:
   *    tags:
   *       - Account
   *    summary: "Sign up Admin"
   *    operationId: signUpAdmin
   *    description: "Use to register an Admin with username, email & password."
   *    parameters:
   *      - in: header
   *        name: x-access-token
   *        schema:
   *          type: string
   *        required: true
   *    requestBody:
   *       content:
   *          application/json:
   *            schema:
   *              type: object
   *              properties:
   *                username:
   *                  description: "Username"
   *                  type: string
   *                  example: test
   *                password:
   *                  description: "Password"
   *                  type: string
   *                  example: test
   *    responses:
   *       '201':
   *         description: "User Created"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: true
   *                message:
   *                  description: "Response Message"
   *                  type: string
   *                  example: User was registered successfully!
   *       '500':
   *         description: "Internal Server error"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *               success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: false
   *               message:
   *                  description: "Response Message"
   *                  type: string
   *                  example: Error message generated by the server
   */
  app.post(
    '/api/auth/signup/admin',
    [verifySignUp.checkDuplicateUsernameOrEmail, authJwt.verifyToken, authJwt.isAdmin],
    controller.signupAdmin
  )

  /**
   * @swagger
   * /api/auth/signup/branch:
   *   post:
   *    tags:
   *       - Account
   *    summary: "Sign up Branch"
   *    operationId: signUpBranch
   *    description: "Use to register a Branch with required options."
   *    parameters:
   *      - in: header
   *        name: x-access-token
   *        schema:
   *          type: string
   *        required: true
   *    requestBody:
   *       content:
   *          application/json:
   *            schema:
   *              type: object
   *              properties:
   *                username:
   *                  description: "Username"
   *                  type: string
   *                  example: test
   *                password:
   *                  description: "Password"
   *                  type: string
   *                  example: test
   *                email:
   *                  description: "Email"
   *                  type: string
   *                  example: test@gmail.com
   *                cameras:
   *                  description: "No. of Cameras to be available"
   *                  type: number
   *                  example: 5
   *                analytics:
   *                  description: "Analytics to be available"
   *                  type: number
   *                  example: testAnalytics
   *                vms:
   *                  description: "VMS"
   *                  type: string
   *                  example: testVMS
   *    responses:
   *       '201':
   *         description: "User Created"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                message:
   *                  description: "Response Message"
   *                  type: string
   *                  example: User was registered successfully!
   *       '500':
   *         description: "Internal Server error"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *               message:
   *                 description: "Response Message"
   *                 type: string
   *                 example: Error message generated by the server
   */
  app.post(
    '/api/auth/signup/branch',
    [verifySignUp.checkDuplicateUsernameOrEmail, authJwt.verifyToken, authJwt.isClient],
    controller.signupBranch
  )

  /**
   * @swagger
   * /api/auth/signup/user:
   *   post:
   *    tags:
   *       - Account
   *    summary: "Sign up User"
   *    operationId: signUpUser
   *    description: "Use to register a User with username, email & password."
   *    parameters:
   *      - in: header
   *        name: x-access-token
   *        schema:
   *          type: string
   *        required: true
   *    requestBody:
   *       content:
   *          application/json:
   *            schema:
   *              type: object
   *              properties:
   *                username:
   *                  description: "Username"
   *                  type: string
   *                  example: test
   *                password:
   *                  description: "Password"
   *                  type: string
   *                  example: test
   *                email:
   *                  description: "Email"
   *                  type: string
   *                  example: test@gmail.com
   *    responses:
   *       '201':
   *         description: "User Created"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: true
   *                message:
   *                  description: "Response Message"
   *                  type: string
   *                  example: User was registered successfully!
   *       '500':
   *         description: "Internal Server error"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *               success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: false
   *               message:
   *                  description: "Response Message"
   *                  type: string
   *                  example: Error message generated by the server
   */
  app.post(
    '/api/auth/signup/user',
    [verifySignUp.checkDuplicateUsernameOrEmail, authJwt.verifyToken, authJwt.isClientOrBranch],
    controller.signupUser
  )

  /**
   * @swagger
   * /api/auth/signinGoogle:
   *   post:
   *    tags:
   *       - Account
   *    summary: "Log In with Google"
   *    operationId: signinGoogle
   *    description: "Use to log in using Google credentials. This method returns the token to be used on every other requests with a length of 12 hours."
   *    requestBody:
   *       content:
   *          application/json:
   *            schema:
   *              type: object
   *              properties:
   *                data:
   *                  description: "Google data"
   *                  type: object
   *                  properties:
   *                    email:
   *                      description: "Email associated with Google"
   *                      type: string
   *                      example: test@graymatics.com
   *    responses:
   *       '200':
   *         description: "A successful response"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: true
   *                user:
   *                  type: object
   *                  properties:
   *                    id:
   *                      description: "Id"
   *                      type: string
   *                      example: 3333-666666-cccccc-nnnnnn
   *                    username:
   *                      description: "Username"
   *                      type: string
   *                      example: test
   *                    email:
   *                      description: "Email"
   *                      type: string
   *                      example: test@graymatics.com
   *                    role:
   *                      description: "Role"
   *                      type: string
   *                      example: client
   *                    id_account:
   *                      description: "Id associated with the general account"
   *                      type: string
   *                      example: 3333-666666-cccccc-nnnnnn
   *                    id_branch:
   *                      description: "Id associated with the branch account"
   *                      type: string
   *                      example: "0000"
   *                    cameras:
   *                      description: "Cameras available for the user"
   *                      type: boolean
   *                      example: 10
   *                    analytics:
   *                      description: "Analytics available for the user"
   *                      type: boolean
   *                      example: 10
   *                    accessToken:
   *                      description: "Security Token"
   *                      type: string
   *                      example: eyJhbGciOiJIUzI1NiIsIiOjE2MTA2NDAwODUsImV4cCI6MTYxM...Zl3afmPKKIMytQtLRDR0k13PQ
   *       '404':
   *         description: "Not found"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: false
   *                message:
   *                  description: "Type of failure"
   *                  type: string
   *                  example: "User is not in the records"
   *                type:
   *                  description: "Error type"
   *                  type: string
   *                  example: user
   *       '401':
   *         description: "User disabled"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: false
   *                message:
   *                  description: "Type of failure"
   *                  type: string
   *                  example: "This account has been disabled, please get in contact with the Administator."
   *                type:
   *                  description: "Error type"
   *                  type: string
   *                  example: disable
   *       '500':
   *         description: "Server error"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: false
   *                message:
   *                  description: "Type of failure"
   *                  type: string
   *                  example: Error message generated by the server
   */
  app.post('/api/auth/signinGoogle', controller.googleLogin)

  /**
   * @swagger
   * /api/auth/signinMS:
   *   post:
   *    tags:
   *       - Account
   *    summary: "Log In with Microsoft"
   *    operationId: signinMS
   *    description: "Use to log in using Microsoft credentials. This method returns the token to be used on every other requests with a length of 12 hours."
   *    requestBody:
   *       content:
   *          application/json:
   *            schema:
   *              type: object
   *              properties:
   *                data:
   *                  description: "Microsoft data"
   *                  type: object
   *                  properties:
   *                    data:
   *                      type: object
   *                      properties:
   *                        account:
   *                          type: object
   *                          properties:
   *                            username:
   *                              description: "Username associated with Microsoft"
   *                              type: string
   *                              example: test
   *    responses:
   *       '200':
   *         description: "A successful response"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: true
   *                user:
   *                  type: object
   *                  properties:
   *                    id:
   *                      description: "Id"
   *                      type: string
   *                      example: 3333-666666-cccccc-nnnnnn
   *                    username:
   *                      description: "Username"
   *                      type: string
   *                      example: test
   *                    email:
   *                      description: "Email"
   *                      type: string
   *                      example: test@graymatics.com
   *                    role:
   *                      description: "Role"
   *                      type: string
   *                      example: client
   *                    id_account:
   *                      description: "Id associated with the general account"
   *                      type: string
   *                      example: 3333-666666-cccccc-nnnnnn
   *                    id_branch:
   *                      description: "Id associated with the branch account"
   *                      type: string
   *                      example: "0000"
   *                    cameras:
   *                      description: "Cameras available for the user"
   *                      type: boolean
   *                      example: 10
   *                    analytics:
   *                      description: "Analytics available for the user"
   *                      type: boolean
   *                      example: 10
   *                    accessToken:
   *                      description: "Security Token"
   *                      type: string
   *                      example: eyJhbGciOiJIUzI1NiIsIiOjE2MTA2NDAwODUsImV4cCI6MTYxM...Zl3afmPKKIMytQtLRDR0k13PQ
   *       '404':
   *         description: "Not found"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: false
   *                message:
   *                  description: "Type of failure"
   *                  type: string
   *                  example: "User is not in the records"
   *                type:
   *                  description: "Error type"
   *                  type: string
   *                  example: user
   *       '401':
   *         description: "User disabled"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: false
   *                message:
   *                  description: "Type of failure"
   *                  type: string
   *                  example: "This account has been disabled, please get in contact with the Administator."
   *                type:
   *                  description: "Error type"
   *                  type: string
   *                  example: disable
   *       '500':
   *         description: "Server error"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: false
   *                message:
   *                  description: "Type of failure"
   *                  type: string
   *                  example: Error message generated by the server
   */
  app.post('/api/auth/signinMs', controller.msLogin)

  /**
   * @swagger
   * /api/auth/signin:
   *   post:
   *    tags:
   *       - Account
   *    summary: "Log In"
   *    operationId: signin
   *    description: "Use to log in using username and password. This method returns the token to be used on every other requests with a length of 12 hours."
   *    requestBody:
   *       content:
   *          application/json:
   *            schema:
   *              type: object
   *              properties:
   *                username:
   *                  description: "Username"
   *                  type: string
   *                  example: test
   *                password:
   *                  description: "Password"
   *                  type: string
   *                  example: test
   *    responses:
   *       '200':
   *         description: "A successful response"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: true
   *                user:
   *                  type: object
   *                  properties:
   *                    id:
   *                      description: "Id"
   *                      type: string
   *                      example: 3333-666666-cccccc-nnnnnn
   *                    username:
   *                      description: "Username"
   *                      type: string
   *                      example: test
   *                    email:
   *                      description: "Email"
   *                      type: string
   *                      example: test@graymatics.com
   *                    role:
   *                      description: "Role"
   *                      type: string
   *                      example: client
   *                    id_account:
   *                      description: "Id associated with the general account"
   *                      type: string
   *                      example: 3333-666666-cccccc-nnnnnn
   *                    id_branch:
   *                      description: "Id associated with the branch account"
   *                      type: string
   *                      example: "0000"
   *                    cameras:
   *                      description: "Cameras available for the user"
   *                      type: boolean
   *                      example: 10
   *                    analytics:
   *                      description: "Analytics available for the user"
   *                      type: boolean
   *                      example: 10
   *                    token:
   *                      description: "Security Token"
   *                      type: string
   *                      example: eyJhbGciOiJIUzI1NiIsIiOjE2MTA2NDAwODUsImV4cCI6MTYxM...Zl3afmPKKIMytQtLRDR0k13PQ
   *       '404':
   *         description: "Not found"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: false
   *                message:
   *                  description: "Type of failure"
   *                  type: string
   *                  example: "User is not in the records"
   *                type:
   *                  description: "Error type"
   *                  type: string
   *                  example: user
   *       '401':
   *         description: "User disabled"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: false
   *                message:
   *                  description: "Type of failure"
   *                  type: string
   *                  example: "This account has been disabled, please get in contact with the Administator."
   *                type:
   *                  description: "Error type"
   *                  type: string
   *                  example: disable
   *       '400':
   *         description: "Invalid Password"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: false
   *                message:
   *                  description: "Type of failure"
   *                  type: string
   *                  example: "Invalid Password"
   *                type:
   *                  description: "Error type"
   *                  type: string
   *                  example: password
   *       '500':
   *         description: "Server error"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: false
   *                message:
   *                  description: "Type of failure"
   *                  type: string
   *                  example: Error message generated by the server
   */
  app.post('/api/auth/signin', controller.signin)

  /**
   * @swagger
   * /api/auth/signout:
   *   post:
   *    tags:
   *       - Account
   *    summary: "Sign Out"
   *    operationId: signout
   *    description: "Use to sign out the user."
   *    requestBody:
   *       content:
   *          application/json:
   *            schema:
   *              type: object
   *              properties:
   *                username:
   *                  description: "Username"
   *                  type: string
   *                  example: test
   *    responses:
   *       '200':
   *         description: "A successful response"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: false
   *                message:
   *                  description: "Success message"
   *                  type: string
   *                  example: "Logged Out"
   *       '500':
   *         description: "Server error"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: false
   *                message:
   *                  description: "Type of failure"
   *                  type: string
   *                  example: Session not found
   */
  app.post('/api/auth/signout', controller.loggOut)

  /**
   * @swagger
   * /api/auth/check:
   *   get:
   *    tags:
   *       - Account
   *    summary: "Check session"
   *    operationId: check
   *    description: "Use to check session of the user."
   *    parameters:
   *      - in: header
   *        name: x-access-token
   *        schema:
   *          type: string
   *        required: true
   *    responses:
   *       '200':
   *         description: "A successful response"
   *         content:
   *           application/json:
   *             schema:
   *              type: object
   *              properties:
   *                success:
   *                  description: "Result type"
   *                  type: boolean
   *                  example: true
   *                message:
   *                  description: "Success Message"
   *                  type: string
   *                  example: Session still active
   */
  app.get('/api/auth/check', [authJwt.verifyToken], controller.check)
}
