const { authJwt, verifyCam } = require('../middleware')
const controller = require('../controllers/camera.controller')

module.exports = function (app) {
  app.use(function (req, res, next) {
    res.header('Access-Control-Allow-Headers', 'x-access-token, Origin, Content-Type, Accept')
    next()
  })
  /**
   * @swagger
   *tags:
   *  name: Cameras
   *  description: API to manage the cameras.
   */

  /**
   * @swagger
   * /api/camera:
   *   post:
   *    tags:
   *       - Cameras
   *    summary: "Add camera"
   *    operationId: add
   *    description: "Use to add a camera for this user"
   *    parameters:
   *      - in: header
   *        name: x-access-token
   *        schema:
   *          type: string
   *        required: true
   *    requestBody:
   *       content:
   *          application/json:
   *            schema:
   *              type: object
   *              properties:
   *                name:
   *                  description: "Name of the camera"
   *                  type: string
   *                  example: test
   *                rtsp_in:
   *                  description: "Rtsp link for the camera to be added"
   *                  type: string
   *                  example: rtsp://192.168.1.210:554/Streaming/Channels/101
   *    responses:
   *      '200':
   *        description: "A successful response"
   *        content:
   *          application/json:
   *            schema:
   *             type: object
   *             properties:
   *               success:
   *                 description: "Result type"
   *                 type: boolean
   *                 example: true
   *               message:
   *                 description: "Message of result"
   *                 type: string
   *                 example: Camera was registered successfully!
   *               id:
   *                 description: "Id for this new camera"
   *                 type: string
   *                 example: cb61166f-8f60-488d-8be8-11a32593b31b
   *      '500':
   *        description: "Server error"
   *        content:
   *          application/json:
   *            schema:
   *             type: object
   *             properties:
   *               success:
   *                 description: "Result type"
   *                 type: boolean
   *                 example: false
   *               message:
   *                 description: "Type of failure"
   *                 type: string
   *                 example: Error message generated by the server
   */
  app.post(
    '/api/camera',
    [authJwt.verifyToken, authJwt.isClientOrBranch, verifyCam.rtsp, verifyCam.numCams],
    controller.addCamera
  )

  /**
   * @swagger
   * /api/camera:
   *   get:
   *    tags:
   *       - Cameras
   *    summary: "Camera listing"
   *    operationId: list
   *    description: "Use to obtain all cameras for this user"
   *    parameters:
   *      - in: header
   *        name: x-access-token
   *        schema:
   *          type: string
   *        required: true
   *    responses:
   *      '200':
   *        description: "A successful response"
   *        content:
   *          application/json:
   *            schema:
   *             type: object
   *             properties:
   *               success:
   *                 description: "Result type"
   *                 type: boolean
   *                 example: true
   *               data:
   *                 type: object
   *                 properties:
   *                   name:
   *                     description: "Name of the camera"
   *                     type: string
   *                     example: Office
   *                   id:
   *                     description: "Id of the camera"
   *                     type: string
   *                     example: 2da2b89d-57a5-4f87-8e54-1809793c3945
   *                   createdAt:
   *                     description: "Date when this camera was created."
   *                     type: date
   *                     example: 2021-02-02T16:17:56.000Z
   *                   updatedAt:
   *                     description: "Date when this camera has been updated."
   *                     type: date
   *                     example: 2021-02-02T16:17:56.000Z
   *      '500':
   *        description: "Server error"
   *        content:
   *          application/json:
   *            schema:
   *             type: object
   *             properties:
   *               success:
   *                 description: "Result type"
   *                 type: boolean
   *                 example: false
   *               message:
   *                 description: "Type of failure"
   *                 type: string
   *                 example: Error message generated by the server
   */

  app.get('/api/camera/', [authJwt.verifyToken], controller.viewCams)

  app.get('/api/camera/viewLiveCams', [authJwt.verifyToken], controller.viewLiveCams)

  app.get(
    '/api/camera/viewOne/:id',
    [authJwt.verifyToken, authJwt.isClientOrBranch],
    controller.viewCam
  )

  app.put(
    '/api/camera/edit/:id',
    [authJwt.verifyToken, authJwt.isClientOrBranch],
    controller.editCam
  )

  app.delete(
    '/api/camera/delete/:id',
    [authJwt.verifyToken, authJwt.isClientOrBranch],
    controller.delCam
  )
}
