const controller = require('../controllers/relations.controller')
const { authJwt, verifyRel } = require('../middleware')

/**
 * @swagger
 *tags:
 *  name: Relations
 *  description: API to manage camera and use cases relations.
 */
module.exports = function (app) {
  app.use(function (req, res, next) {
    res.header('Access-Control-Allow-Headers', 'x-access-token, Origin, Content-Type, Accept')
    next()
  })

  /**
   * @swagger
   * /api/relations/cam/{id}:
   *   get:
   *    tags:
   *       - Relations
   *    summary: "Camera Relations"
   *    operationId: getRels
   *    description: "Use to get all use cases assgnied to camera"
   *    parameters:
   *      - in: path
   *        name: id
   *        schema:
   *          type: string
   *        required: true
   *      - in: header
   *        name: x-access-token
   *        schema:
   *          type: string
   *        required: true
   *    responses:
   *      '200':
   *        description: "A successful response"
   *        content:
   *          application/json:
   *            schema:
   *             type: object
   *             properties:
   *               success:
   *                 description: "Result type"
   *                 type: boolean
   *                 example: true
   *               data:
   *                 type: object
   *                 example : {"id": 47,"camera_id": "fa9e5b11-0998-472d-aad0-67c5bf0e6d27","algo_id": 8,"roi_id": [{"x": 0.6454635045371354,"y": -0.8092867290389464}, {"x": 388.99824657955025,"y": 0.8682630898595983 },{"x": 382.2880473039561, "y": 239.91911228290223},{"x": -1.0320863143614094,"y": 231.5313631884095}],"atributes": [{"conf": 95,"save": false,"time": 0 }],"id_account": "2783e08d-4853-40d8-8319-409d811e2b6e","id_branch": "2783e08d-4853-40d8-8319-409d811e2b6e","stream": null,"http_out": null,"createdAt": "2021-01-26T15:10:53.000Z","updatedAt": "2021-05-17T17:49:57.000Z","algo_name": "Wrong way or illegal turn detection","table": "direction","alert": true}
   *      '500':
   *        description: "Server error"
   *        content:
   *          application/json:
   *            schema:
   *             type: object
   *             properties:
   *               success:
   *                 description: "Result type"
   *                 type: boolean
   *                 example: false
   *               message:
   *                 description: "Type of failure"
   *                 type: string
   *                 example: Error message generated by the server
   */
  app.get(
    '/api/relations/cam/:id',
    [authJwt.verifyToken, authJwt.isClientOrBranch],
    controller.getRels
  )

  app.get(
    '/api/relations/dashboards',
    [authJwt.verifyToken, authJwt.isClientOrBranchOrAdmin],
    controller.dashboards
  )

  app.get('/api/relations/all', [authJwt.verifyToken], controller.getAll)

  app.post(
    '/api/relations/create',
    [authJwt.verifyToken, authJwt.isClientOrBranch, verifyRel.numRels],
    controller.createRel
  )

  app.delete(
    '/api/relations/del/:id',
    [authJwt.verifyToken, authJwt.isClientOrBranch],
    controller.deleteRel
  )

  app.put(
    '/api/relations/edit/:id',
    [authJwt.verifyToken, authJwt.isClientOrBranch],
    controller.editRel
  )

  app.post(
    '/api/camConf/:id',
    [authJwt.verifyToken, authJwt.isClientOrBranch, verifyRel.numRels],
    controller.configs
  )

  app.post(
    '/api/roiConf/:id',
    [authJwt.verifyToken, authJwt.isClientOrBranch],
    controller.configsRoi
  )

  app.get('/api/relations/check/:id/:cam', [authJwt.verifyToken], controller.checkVideo)
}
